### ISSUE TITLE
arm linux部署

### ISSUE THREAD

**Issue by mortalGeorge** [OpenCSGs/csghub-installer#77]
使用docker compose部署，是否可以在arm架构linux系统部署？部分镜像如opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest、opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/registry:2是否有arm版？

**Comment by MasonXon** [comment]
All docker images compatible with platform linux/amd64 and linux/arm64, are you unable to pull any image?

**Comment by mortalGeorge** [comment]
docker pull --platform linux/arm64 opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/registry:2
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/gradescope/postgresql-multiple-databases:14.4
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/governmentpaas/psql:329
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/bitnami/minio:2023

提示image with reference opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

**Comment by mortalGeorge** [comment]
> All docker images compatible with platform linux/amd64 and linux/arm64, are you unable to pull any image?

docker pull --platform linux/arm64 opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/registry:2
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/gradescope/postgresql-multiple-databases:14.4
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/governmentpaas/psql:329
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/bitnami/minio:2023

提示image with reference opencsg-registry.cn-beijing.cr.aliyuncs.com/public/nginx:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

**Comment by MasonXon** [comment]
Please change image nginx from namespace public to opencsg_public, 
example: 
replace with `opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/nginx:latest`

**Comment by mortalGeorge** [comment]
> Please change image nginx from namespace public to opencsg_public, example: replace with `opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/nginx:latest`

nginx确实可以了，但是下面几个还是没有
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/registry:2
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/gradescope/postgresql-multiple-databases:14.4
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/governmentpaas/psql:329
opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/bitnami/minio:2023

**Comment by MasonXon** [comment]
Please try again.
